language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t casey025682/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true casey025682/react-test npm run test

after_success:
  - docker build -t casey025682/multi-client ./client
  - docker build -t casey025682/multi-nginx ./nginx
  - docker build -t casey025682/multi-server ./server
  - docker build -t casey025682/multi-worker ./worker
  # Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push casey025682/multi-client
  - docker push casey025682/multi-nginx
  - docker push casey025682/multi-server
  - docker push casey025682/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-east-1-114064149276"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
